system:
  port: 10000
  successCode: 1
  successMessage: Success
  errorCode: 0
  errorMessage: Failed

postgres:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: 123456
  database: szzn_admin

rpc:
  host: 0.0.0.0
  port: 10001
